# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: '8cb5a9da-35e2-4695-86f3-e9f9877d354d/f2f0f529-fd21-45ee-8bdd-8a6e331b2633'

- script: |
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '8cb5a9da-35e2-4695-86f3-e9f9877d354d/f2f0f529-fd21-45ee-8bdd-8a6e331b2633'
    vstsFeedPackagePublish: 'f'
    versionOption: 'minor'

- task: WhiteSource Bolt@19
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'